<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Version>1.1.0</Version>
    <Authors>RyoTune</Authors>
    <RepositoryUrl>https://github.com/RyoTune/BGME.BattleThemes</RepositoryUrl>
  </PropertyGroup>

</Project>
